version: "3"
services:
  postgres:
    image: postgres:alpine
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
  rso-customers:
    image: rlamp/lairbnb-users
    ports:
      - 8080:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/users
    depends_on:
      - postgres