kumuluzee:
  name: lairbnb-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/users
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  health:
    servlet:
        mapping: /health
        enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/UsersDS
      etcd-health-check:
        connection-url: http://192.168.99.100:2379/health
      http-health-check:
        - connection-url: http://192.168.99.100:8081/v1/lairs
        - connection-url: http://192.168.99.100:8082/v1/reservations

properties:
  external-services:
    reservation-service:
      enabled: true
    lair-service:
      enabled: true
  service:
    healthy: true
    persistence:
      create:
        allowed: true
      delete:
        allowed: false
