kumuluzee:
  name: lairbnb-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/users
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379

properties:
  external-services:
    reservation-service:
      enabled: true
    lair-service:
      enabled: true
  service:
    persistence:
      create:
        allowed: true
      delete:
        allowed: false