kumuluzee:
  name: lairbnb-users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/users
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        jndi-name: jdbc/UsersDS
      etcd-health-check:
        - connection-url: http://localhost:2379/health
          connection-url: http://192.168.99.100:2379/health
          connection-url: http://etcd:2379/health
      http-health-check:
        - connection-url: http://192.168.99.100:8081/v1/lairs
          connection-url: http://localhost:8081/v1/lairs
          connection-url: http://lairs:8081/v1/lairs
        - connection-url: http://192.168.99.100:8082/v1/reservations
          connection-url: http://localhost:8082/v1/reservations
          connection-url: http://reservations:8082/v1/reservations
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
    - name: users-endpoint
      url-pattern: /v1/users/*
      status-codes: "200, 404, 500"
    - name: demo-endpoint
      url-pattern: /v1/demo/*
      status-codes: "200"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="notifications">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="9133958c-d366-47ba-8103-32d02e80e198-ls.logit.io" port="14664"
                                                                                                        protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8"
                                                                                                    properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="trace"/>
                          </Root>
                      </Loggers>
                  </Configuration>'

properties:
  external-services:
    reservation-service:
      enabled: true
    lair-service:
      enabled: true
  service:
    healthy: true
    persistence:
      create:
        allowed: true
      delete:
        allowed: false
