apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: rlamp/lairbnb-users:latest
        name: users
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-users:5432/users
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://168.1.149.132:32147
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: users
